package nisargpatel.deadreckoning.domain.state

data class SensorState(
    val accelX: Float = 0f,
    val accelY: Float = 0f,
    val accelZ: Float = 0f,
    val accelMagnitude: Float = 0f,
    val gyroX: Float = 0f,
    val gyroY: Float = 0f,
    val gyroZ: Float = 0f,
    val gyroBiasX: Float = 0f,
    val gyroBiasY: Float = 0f,
    val gyroBiasZ: Float = 0f,
    val magX: Float = 0f,
    val magY: Float = 0f,
    val magZ: Float = 0f,
    val rollDegrees: Float = 0f,
    val pitchDegrees: Float = 0f,
    val yawDegrees: Float = 0f,
    val vehicleHeadingDegrees: Float = 0f,
    val yawAlignmentOffsetDegrees: Float = 0f,
    val mountStabilityPercentage: Int = 0,
    val alignmentConfidencePercentage: Int = 0,
    val isStationary: Boolean = false,
    val isMountChanged: Boolean = false,
    val usesRotationVector: Boolean = false,
    val imuSamplingHz: Int = 0,
    val overallHealthPercentage: Int = 0,
    val isAccelAvailable: Boolean = true,
    val isGyroAvailable: Boolean = true,
    val isMagAvailable: Boolean = true
)
